
" This is my vimrc file.

" Turns on syntax highlighting
syntax on

" Turns on numbering
set number
set relativenumber

" Sets splitting from the right
set splitright

" utf-8 encoding
set encoding=utf-8

" setup indenting
filetype plugin indent on
set autoindent
